
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 96emisun
 */
public class RegGUI extends javax.swing.JFrame {
    
    private Library lib;
    private String filnamn;
    
    /**
     * Creates new form RegGUI
     */
    public RegGUI() {
        initComponents();
        lib = new Library();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        pnlTab1 = new javax.swing.JPanel();
        rbtnFilm = new javax.swing.JRadioButton();
        rbtnMusik = new javax.swing.JRadioButton();
        rbtnSpel = new javax.swing.JRadioButton();
        lblNamn = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblÅr = new javax.swing.JLabel();
        txfNamn = new javax.swing.JTextField();
        txfGenre = new javax.swing.JTextField();
        txfÅr = new javax.swing.JTextField();
        btnLäggTill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaUtskrift = new javax.swing.JTextArea();
        btnVäljFil = new javax.swing.JButton();
        btnLäs = new javax.swing.JButton();
        pnlTab2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register_Emil_Sundqvist");

        btnGroup.add(rbtnFilm);
        rbtnFilm.setText("Film");

        btnGroup.add(rbtnMusik);
        rbtnMusik.setText("Musik");

        btnGroup.add(rbtnSpel);
        rbtnSpel.setText("Spel");

        lblNamn.setText("Namn:");

        lblGenre.setText("Genre:");

        lblÅr.setText("År:");

        btnLäggTill.setText("Lägg Till");
        btnLäggTill.setMaximumSize(new java.awt.Dimension(85, 23));
        btnLäggTill.setMinimumSize(new java.awt.Dimension(85, 23));
        btnLäggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäggTillActionPerformed(evt);
            }
        });

        txaUtskrift.setColumns(20);
        txaUtskrift.setRows(5);
        jScrollPane1.setViewportView(txaUtskrift);

        btnVäljFil.setText("Välj Fil");
        btnVäljFil.setMaximumSize(new java.awt.Dimension(85, 23));
        btnVäljFil.setMinimumSize(new java.awt.Dimension(85, 23));
        btnVäljFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVäljFilActionPerformed(evt);
            }
        });

        btnLäs.setText("Läs Innehåll");
        btnLäs.setMaximumSize(new java.awt.Dimension(85, 23));
        btnLäs.setMinimumSize(new java.awt.Dimension(85, 23));
        btnLäs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTab1Layout = new javax.swing.GroupLayout(pnlTab1);
        pnlTab1.setLayout(pnlTab1Layout);
        pnlTab1Layout.setHorizontalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlTab1Layout.createSequentialGroup()
                        .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTab1Layout.createSequentialGroup()
                                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnMusik)
                                    .addComponent(rbtnSpel)
                                    .addComponent(rbtnFilm))
                                .addGap(16, 16, 16)
                                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblÅr)
                                    .addComponent(lblNamn)
                                    .addComponent(lblGenre))
                                .addGap(18, 18, 18)
                                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(txfGenre)
                                    .addComponent(txfÅr)))
                            .addGroup(pnlTab1Layout.createSequentialGroup()
                                .addComponent(btnVäljFil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLäggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLäs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTab1Layout.setVerticalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFilm)
                    .addComponent(lblNamn)
                    .addComponent(txfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMusik)
                    .addComponent(lblGenre)
                    .addComponent(txfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSpel)
                    .addComponent(lblÅr)
                    .addComponent(txfÅr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLäggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVäljFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLäs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab1", pnlTab1);

        javax.swing.GroupLayout pnlTab2Layout = new javax.swing.GroupLayout(pnlTab2);
        pnlTab2.setLayout(pnlTab2Layout);
        pnlTab2Layout.setHorizontalGroup(
            pnlTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        pnlTab2Layout.setVerticalGroup(
            pnlTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab2", pnlTab2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVäljFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVäljFilActionPerformed
        lib.väljFil();
        filnamn = lib.getFilnamn();
    }//GEN-LAST:event_btnVäljFilActionPerformed

    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
        
        AbstractItemWIP item = null;
        
        if(filnamn == null){
            System.out.println("Du måste välja en fil att skriva till");
        }
        else{
            
            lib.checkFileExistence(filnamn);
            
            if(rbtnFilm.isSelected()){
                item = new Film(txfNamn.getText(), txfGenre.getText(), txfÅr.getText());
            }
            else if(rbtnMusik.isSelected()){
                item = new Musik(txfNamn.getText(), txfGenre.getText(), txfÅr.getText());
            }
            else if(rbtnSpel.isSelected()){
                item = new Spel(txfNamn.getText(), txfGenre.getText(), txfÅr.getText());
            }

            lib.writeToCSV(filnamn, item);

            txfNamn.setText("");
            txfGenre.setText("");
            txfÅr.setText("");
            
        }
    }//GEN-LAST:event_btnLäggTillActionPerformed

    private void btnLäsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäsActionPerformed
        txaUtskrift.setText("");
        
        ArrayList<AbstractItem> info = lib.readFromCSV(filnamn);
        String[] rubriker = null;
        
        try {
            rubriker = lib.getRubriker(filnamn);
        } catch (IOException ex) {
            System.out.println("Någonting gick fel");
        }
        //FIXA SÅ ATT RUBRIKER-FUNKTIONEN FUNKAR
        for(AbstractItem abItem : info){
            txaUtskrift.append(
                    rubriker[0] + ": " + abItem.getNamn() + "\n" + 
                    rubriker[1] + ": " + abItem.getGenre() + "\n" + 
                    rubriker[2] + ": " + abItem.getÅr() + "\n" +
                    rubriker[3] + ": " + abItem.getTyp() + "\n\n");
        }
    }//GEN-LAST:event_btnLäsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnLäs;
    private javax.swing.JButton btnVäljFil;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblÅr;
    private javax.swing.JPanel pnlTab1;
    private javax.swing.JPanel pnlTab2;
    private javax.swing.JRadioButton rbtnFilm;
    private javax.swing.JRadioButton rbtnMusik;
    private javax.swing.JRadioButton rbtnSpel;
    private javax.swing.JTextArea txaUtskrift;
    private javax.swing.JTextField txfGenre;
    private javax.swing.JTextField txfNamn;
    private javax.swing.JTextField txfÅr;
    // End of variables declaration//GEN-END:variables
}
