
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 96emisun
 */
public class RegGUI extends javax.swing.JFrame {
    
    private Library lib;
    private String filename;
    
    /**
     * Creates new form RegGUI
     */
    public RegGUI() {
        initComponents();
        lib = new Library();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        pnlTab1 = new javax.swing.JPanel();
        rbtnMovie = new javax.swing.JRadioButton();
        rbtnMusic = new javax.swing.JRadioButton();
        rbtnGame = new javax.swing.JRadioButton();
        lblName = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        txfGenre = new javax.swing.JTextField();
        txfYear = new javax.swing.JTextField();
        btnAddCSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPrint = new javax.swing.JTextArea();
        btnChooseFile = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        cbSort = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddXML = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlTab2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register_Emil_Sundqvist");

        btnGroup.add(rbtnMovie);
        rbtnMovie.setText("Movie");

        btnGroup.add(rbtnMusic);
        rbtnMusic.setText("Music");

        btnGroup.add(rbtnGame);
        rbtnGame.setText("Game");

        lblName.setText("Name:");

        lblGenre.setText("Genre:");

        lblYear.setText("Year:");

        btnAddCSV.setText("Save as CSV");
        btnAddCSV.setMaximumSize(new java.awt.Dimension(85, 23));
        btnAddCSV.setMinimumSize(new java.awt.Dimension(85, 23));
        btnAddCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCSVActionPerformed(evt);
            }
        });

        txaPrint.setColumns(20);
        txaPrint.setRows(5);
        jScrollPane1.setViewportView(txaPrint);

        btnChooseFile.setText("Choose Library");
        btnChooseFile.setMaximumSize(new java.awt.Dimension(85, 23));
        btnChooseFile.setMinimumSize(new java.awt.Dimension(85, 23));
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        btnRead.setText("Read From CSV");
        btnRead.setMaximumSize(new java.awt.Dimension(85, 23));
        btnRead.setMinimumSize(new java.awt.Dimension(85, 23));
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        cbSort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Genre", "Year", "Type" }));

        jLabel1.setText("Sort the list based on:");

        jLabel2.setText("Choose the type of object and enter it's information:");

        jLabel3.setText("Choose which library you want to save to or read from:");

        jLabel4.setText("Save the information to the selected library:");

        btnAddXML.setText("Save as XML");
        btnAddXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddXMLActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose how to sort the library and then read from it:");

        jButton1.setText("Read From XML");

        javax.swing.GroupLayout pnlTab1Layout = new javax.swing.GroupLayout(pnlTab1);
        pnlTab1.setLayout(pnlTab1Layout);
        pnlTab1Layout.setHorizontalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTab1Layout.createSequentialGroup()
                        .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnMusic)
                            .addComponent(rbtnGame)
                            .addComponent(rbtnMovie))
                        .addGap(16, 16, 16)
                        .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYear)
                            .addComponent(lblName)
                            .addComponent(lblGenre))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfName, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txfGenre)
                            .addComponent(txfYear)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(pnlTab1Layout.createSequentialGroup()
                        .addComponent(btnAddCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddXML, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTab1Layout.createSequentialGroup()
                        .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbSort, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRead, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlTab1Layout.setVerticalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMovie)
                    .addComponent(lblName)
                    .addComponent(txfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMusic)
                    .addComponent(lblGenre)
                    .addComponent(txfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnGame)
                    .addComponent(lblYear)
                    .addComponent(txfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddXML)
                    .addComponent(btnAddCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(226, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        jTabbedPane3.addTab("Library", pnlTab1);

        javax.swing.GroupLayout pnlTab2Layout = new javax.swing.GroupLayout(pnlTab2);
        pnlTab2.setLayout(pnlTab2Layout);
        pnlTab2Layout.setHorizontalGroup(
            pnlTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        pnlTab2Layout.setVerticalGroup(
            pnlTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab2", pnlTab2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        lib.chooseFile();
        filename = lib.getFilename();
    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void btnAddCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCSVActionPerformed
        
        AbstractItem item = null;
        
        if(filename == null){
            JOptionPane.showMessageDialog(null, "You have not chosen a file to write to"); 
        }
        else{
            
            lib.checkFileExistence(filename);
            
            if(rbtnMovie.isSelected()){
                item = new Movie(txfName.getText(), txfGenre.getText(), txfYear.getText(), null);
            }
            else if(rbtnMusic.isSelected()){
                item = new Music(txfName.getText(), txfGenre.getText(), txfYear.getText(), null);
            }
            else if(rbtnGame.isSelected()){
                item = new Game(txfName.getText(), txfGenre.getText(), txfYear.getText(), null);
            }

            if(lib.writeToCSV(filename, item)){
                txfName.setText("");
                txfGenre.setText("");
                txfYear.setText("");
            }
        }
    }//GEN-LAST:event_btnAddCSVActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        txaPrint.setText("");
        
        String sorting = String.valueOf(cbSort.getSelectedItem());
        
        ArrayList<AbstractItem> info = lib.readFromCSV(filename, sorting);
        String[] headlines = null;
        
        try {
            headlines = lib.getHeadlines(filename);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong"); 
        }
        
        for(AbstractItem abItem : info){
            txaPrint.append(
                    headlines[0] + ": " + abItem.getName() + "\n" + 
                    headlines[1] + ": " + abItem.getGenre() + "\n" + 
                    headlines[2] + ": " + abItem.getYear() + "\n" +
                    headlines[3] + ": " + abItem.getType() + "\n\n");
        }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnAddXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddXMLActionPerformed
        AbstractItem item = null;
        
        if(filename == null){
            JOptionPane.showMessageDialog(null, "You have not chosen a file to write to"); 
        }
        else{
            
            //lib.checkFileExistence(filename);
            
            if(rbtnMovie.isSelected()){
                item = new Movie(txfName.getText(), txfGenre.getText(), txfYear.getText(), null);
            }
            else if(rbtnMusic.isSelected()){
                item = new Music(txfName.getText(), txfGenre.getText(), txfYear.getText(), null);
            }
            else if(rbtnGame.isSelected()){
                item = new Game(txfName.getText(), txfGenre.getText(), txfYear.getText(), null);
            }

            if(lib.writeToXML(filename, item)){
                txfName.setText("");
                txfGenre.setText("");
                txfYear.setText("");
            }
        }
    }//GEN-LAST:event_btnAddXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCSV;
    private javax.swing.JButton btnAddXML;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnRead;
    private javax.swing.JComboBox cbSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnlTab1;
    private javax.swing.JPanel pnlTab2;
    private javax.swing.JRadioButton rbtnGame;
    private javax.swing.JRadioButton rbtnMovie;
    private javax.swing.JRadioButton rbtnMusic;
    private javax.swing.JTextArea txaPrint;
    private javax.swing.JTextField txfGenre;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfYear;
    // End of variables declaration//GEN-END:variables
}
